begin;
create extension if not exists pgtap with schema extensions;
set local search_path=public,extensions;
select no_plan();
insert into auth.users(id,email,email_confirmed_at) values(md5('u11')::uuid,'user11@example.invalid',clock_timestamp());
insert into auth.users(id,email,email_confirmed_at) values(md5('u12')::uuid,'user12@example.invalid',clock_timestamp());
insert into auth.users(id,email,email_confirmed_at) values(md5('u13')::uuid,'user13@example.invalid',clock_timestamp());
select private.bootstrap_organization(md5('o1')::uuid,'Synthetic 1',md5('u11')::uuid,md5('b1')::uuid);
update public.memberships set id=md5('m11')::uuid where organization_id=md5('o1')::uuid;
insert into public.memberships(id,organization_id,auth_user_id,role) values(md5('m12')::uuid,md5('o1')::uuid,md5('u12')::uuid,'ADMIN');
insert into public.memberships(id,organization_id,auth_user_id,role) values(md5('m13')::uuid,md5('o1')::uuid,md5('u13')::uuid,'EMPLOYEE');
insert into public.employees(id,organization_id,code,display_name,membership_id) values(md5('e11')::uuid,md5('o1')::uuid,'E1','Synthetic',md5('m11')::uuid);
insert into public.employees(id,organization_id,code,display_name,membership_id) values(md5('e12')::uuid,md5('o1')::uuid,'E2','Synthetic',md5('m12')::uuid);
insert into public.employees(id,organization_id,code,display_name,membership_id) values(md5('e13')::uuid,md5('o1')::uuid,'E3','Synthetic',md5('m13')::uuid);
insert into public.employees(id,organization_id,code,display_name) values(md5('e14')::uuid,md5('o1')::uuid,'NOEMAIL','No email');
insert into auth.users(id,email,email_confirmed_at) values(md5('u21')::uuid,'user21@example.invalid',clock_timestamp());
insert into auth.users(id,email,email_confirmed_at) values(md5('u22')::uuid,'user22@example.invalid',clock_timestamp());
insert into auth.users(id,email,email_confirmed_at) values(md5('u23')::uuid,'user23@example.invalid',clock_timestamp());
select private.bootstrap_organization(md5('o2')::uuid,'Synthetic 2',md5('u21')::uuid,md5('b2')::uuid);
update public.memberships set id=md5('m21')::uuid where organization_id=md5('o2')::uuid;
insert into public.memberships(id,organization_id,auth_user_id,role) values(md5('m22')::uuid,md5('o2')::uuid,md5('u22')::uuid,'ADMIN');
insert into public.memberships(id,organization_id,auth_user_id,role) values(md5('m23')::uuid,md5('o2')::uuid,md5('u23')::uuid,'EMPLOYEE');
insert into public.employees(id,organization_id,code,display_name,membership_id) values(md5('e21')::uuid,md5('o2')::uuid,'E1','Synthetic',md5('m21')::uuid);
insert into public.employees(id,organization_id,code,display_name,membership_id) values(md5('e22')::uuid,md5('o2')::uuid,'E2','Synthetic',md5('m22')::uuid);
insert into public.employees(id,organization_id,code,display_name,membership_id) values(md5('e23')::uuid,md5('o2')::uuid,'E3','Synthetic',md5('m23')::uuid);
insert into public.employees(id,organization_id,code,display_name) values(md5('e24')::uuid,md5('o2')::uuid,'NOEMAIL','No email');
set constraints all immediate;
select ok(((select relrowsecurity and relforcerowsecurity from pg_class where oid='public.organizations'::regclass)),'FORCE RLS organizations');
select ok(((select relrowsecurity and relforcerowsecurity from pg_class where oid='public.memberships'::regclass)),'FORCE RLS memberships');
select ok(((select relrowsecurity and relforcerowsecurity from pg_class where oid='public.employees'::regclass)),'FORCE RLS employees');
select ok(((select relrowsecurity and relforcerowsecurity from pg_class where oid='public.audit_log'::regclass)),'FORCE RLS audit_log');
select ok(((select not rolcanlogin and not rolsuper and not rolbypassrls and not rolcreaterole from pg_roles where rolname='fichaje_reader')),'minimal role fichaje_reader');
select ok((not pg_has_role('authenticated','fichaje_reader','MEMBER')),'no role inheritance fichaje_reader');
select ok(((select not rolcanlogin and not rolsuper and not rolbypassrls and not rolcreaterole from pg_roles where rolname='fichaje_writer')),'minimal role fichaje_writer');
select ok((not pg_has_role('authenticated','fichaje_writer','MEMBER')),'no role inheritance fichaje_writer');
select ok((not has_schema_privilege('authenticated','private','USAGE')),'private schema hidden');
select ok((not exists(select 1 from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname in ('public','private') and p.prosecdef and not coalesce(p.proconfig @> array['search_path=""'],false))),'definer search paths empty');
reset role;
select set_config('request.jwt.claims',jsonb_build_object('sub',md5('u11')::uuid,'role','authenticated')::text,true);
set local role authenticated;
select ok(((select count(*) from public.organizations)=1),'TEN-01 1 OWNER own organization');
select ok(((select count(*) from public.memberships)=3),'TEN-01 1 OWNER memberships');
select ok(((select count(*) from public.employees)=4),'TEN-01 1 OWNER employees');
select ok((not exists(select 1 from public.employees where organization_id=md5('o2')::uuid)),'TEN-03 1 OWNER foreign UUID');
select ok((not exists(select 1 from public.employees e join public.memberships m on e.membership_id=m.id where m.organization_id=md5('o2')::uuid)),'TEN-05 1 OWNER join');
select throws_ok($test$select public.manage_employee(md5('o2')::uuid,gen_random_uuid(),md5('evil')::uuid,0,'X','X',null,true)$test$,'42501','FORBIDDEN','TEN-02 1 OWNER cross RPC');
select throws_ok($test$update public.memberships set role='OWNER'$test$,'42501',NULL,'ROLE-01 1 OWNER direct write denied');
select throws_ok($test$truncate public.employees$test$,'42501',NULL,'1 OWNER truncate denied');
reset role;
select set_config('request.jwt.claims',jsonb_build_object('sub',md5('u12')::uuid,'role','authenticated')::text,true);
set local role authenticated;
select ok(((select count(*) from public.organizations)=1),'TEN-01 1 ADMIN own organization');
select ok(((select count(*) from public.memberships)=3),'TEN-01 1 ADMIN memberships');
select ok(((select count(*) from public.employees)=4),'TEN-01 1 ADMIN employees');
select ok((not exists(select 1 from public.employees where organization_id=md5('o2')::uuid)),'TEN-03 1 ADMIN foreign UUID');
select ok((not exists(select 1 from public.employees e join public.memberships m on e.membership_id=m.id where m.organization_id=md5('o2')::uuid)),'TEN-05 1 ADMIN join');
select throws_ok($test$select public.manage_employee(md5('o2')::uuid,gen_random_uuid(),md5('evil')::uuid,0,'X','X',null,true)$test$,'42501','FORBIDDEN','TEN-02 1 ADMIN cross RPC');
select throws_ok($test$update public.memberships set role='OWNER'$test$,'42501',NULL,'ROLE-01 1 ADMIN direct write denied');
select throws_ok($test$truncate public.employees$test$,'42501',NULL,'1 ADMIN truncate denied');
reset role;
select set_config('request.jwt.claims',jsonb_build_object('sub',md5('u13')::uuid,'role','authenticated')::text,true);
set local role authenticated;
select ok(((select count(*) from public.organizations)=1),'TEN-01 1 EMPLOYEE own organization');
select ok(((select count(*) from public.memberships)=1),'TEN-01 1 EMPLOYEE memberships');
select ok(((select count(*) from public.employees)=1),'TEN-01 1 EMPLOYEE employees');
select ok((not exists(select 1 from public.employees where organization_id=md5('o2')::uuid)),'TEN-03 1 EMPLOYEE foreign UUID');
select ok((not exists(select 1 from public.employees e join public.memberships m on e.membership_id=m.id where m.organization_id=md5('o2')::uuid)),'TEN-05 1 EMPLOYEE join');
select throws_ok($test$select public.manage_employee(md5('o2')::uuid,gen_random_uuid(),md5('evil')::uuid,0,'X','X',null,true)$test$,'42501','FORBIDDEN','TEN-02 1 EMPLOYEE cross RPC');
select throws_ok($test$update public.memberships set role='OWNER'$test$,'42501',NULL,'ROLE-01 1 EMPLOYEE direct write denied');
select throws_ok($test$truncate public.employees$test$,'42501',NULL,'1 EMPLOYEE truncate denied');
reset role;
select set_config('request.jwt.claims',jsonb_build_object('sub',md5('u21')::uuid,'role','authenticated')::text,true);
set local role authenticated;
select ok(((select count(*) from public.organizations)=1),'TEN-01 2 OWNER own organization');
select ok(((select count(*) from public.memberships)=3),'TEN-01 2 OWNER memberships');
select ok(((select count(*) from public.employees)=4),'TEN-01 2 OWNER employees');
select ok((not exists(select 1 from public.employees where organization_id=md5('o1')::uuid)),'TEN-03 2 OWNER foreign UUID');
select ok((not exists(select 1 from public.employees e join public.memberships m on e.membership_id=m.id where m.organization_id=md5('o1')::uuid)),'TEN-05 2 OWNER join');
select throws_ok($test$select public.manage_employee(md5('o1')::uuid,gen_random_uuid(),md5('evil')::uuid,0,'X','X',null,true)$test$,'42501','FORBIDDEN','TEN-02 2 OWNER cross RPC');
select throws_ok($test$update public.memberships set role='OWNER'$test$,'42501',NULL,'ROLE-01 2 OWNER direct write denied');
select throws_ok($test$truncate public.employees$test$,'42501',NULL,'2 OWNER truncate denied');
reset role;
select set_config('request.jwt.claims',jsonb_build_object('sub',md5('u22')::uuid,'role','authenticated')::text,true);
set local role authenticated;
select ok(((select count(*) from public.organizations)=1),'TEN-01 2 ADMIN own organization');
select ok(((select count(*) from public.memberships)=3),'TEN-01 2 ADMIN memberships');
select ok(((select count(*) from public.employees)=4),'TEN-01 2 ADMIN employees');
select ok((not exists(select 1 from public.employees where organization_id=md5('o1')::uuid)),'TEN-03 2 ADMIN foreign UUID');
select ok((not exists(select 1 from public.employees e join public.memberships m on e.membership_id=m.id where m.organization_id=md5('o1')::uuid)),'TEN-05 2 ADMIN join');
select throws_ok($test$select public.manage_employee(md5('o1')::uuid,gen_random_uuid(),md5('evil')::uuid,0,'X','X',null,true)$test$,'42501','FORBIDDEN','TEN-02 2 ADMIN cross RPC');
select throws_ok($test$update public.memberships set role='OWNER'$test$,'42501',NULL,'ROLE-01 2 ADMIN direct write denied');
select throws_ok($test$truncate public.employees$test$,'42501',NULL,'2 ADMIN truncate denied');
reset role;
select set_config('request.jwt.claims',jsonb_build_object('sub',md5('u23')::uuid,'role','authenticated')::text,true);
set local role authenticated;
select ok(((select count(*) from public.organizations)=1),'TEN-01 2 EMPLOYEE own organization');
select ok(((select count(*) from public.memberships)=1),'TEN-01 2 EMPLOYEE memberships');
select ok(((select count(*) from public.employees)=1),'TEN-01 2 EMPLOYEE employees');
select ok((not exists(select 1 from public.employees where organization_id=md5('o1')::uuid)),'TEN-03 2 EMPLOYEE foreign UUID');
select ok((not exists(select 1 from public.employees e join public.memberships m on e.membership_id=m.id where m.organization_id=md5('o1')::uuid)),'TEN-05 2 EMPLOYEE join');
select throws_ok($test$select public.manage_employee(md5('o1')::uuid,gen_random_uuid(),md5('evil')::uuid,0,'X','X',null,true)$test$,'42501','FORBIDDEN','TEN-02 2 EMPLOYEE cross RPC');
select throws_ok($test$update public.memberships set role='OWNER'$test$,'42501',NULL,'ROLE-01 2 EMPLOYEE direct write denied');
select throws_ok($test$truncate public.employees$test$,'42501',NULL,'2 EMPLOYEE truncate denied');
reset role;
select set_config('request.jwt.claims',jsonb_build_object('sub',md5('u13')::uuid,'role','authenticated')::text,true);
set local role authenticated;
select throws_ok($test$select public.manage_membership(md5('o1')::uuid,gen_random_uuid(),md5('m13')::uuid,1,'ADMIN',true)$test$,'42501','FORBIDDEN','ROLE-01 no self elevation');
select throws_ok($test$select public.manage_employee(md5('o1')::uuid,gen_random_uuid(),md5('evil')::uuid,0,'X','X',null,true)$test$,'42501','FORBIDDEN','employee cannot create employees');
reset role;
select set_config('request.jwt.claims',jsonb_build_object('sub',md5('u12')::uuid,'role','authenticated')::text,true);
set local role authenticated;
select throws_ok($test$select public.manage_membership(md5('o1')::uuid,gen_random_uuid(),md5('m11')::uuid,1,'EMPLOYEE',false)$test$,'42501','FORBIDDEN','ROLE-02 ADMIN cannot manage OWNER');
select throws_ok($test$select public.manage_membership(md5('o1')::uuid,gen_random_uuid(),md5('m13')::uuid,1,'ADMIN',true)$test$,'42501','FORBIDDEN','ROLE-02 ADMIN cannot promote');
select throws_ok($test$select public.transfer_ownership(md5('o1')::uuid,gen_random_uuid(),md5('m13')::uuid,1)$test$,'42501','FORBIDDEN','ROLE-02 ADMIN cannot transfer');
select throws_ok($test$select public.manage_employee(md5('o1')::uuid,gen_random_uuid(),md5('evil')::uuid,0,'X','X',md5('m23')::uuid,true)$test$,'42501','FORBIDDEN','TEN-04 RPC foreign membership');
reset role;
select throws_ok($test$insert into public.employees(organization_id,code,display_name,membership_id) values(md5('o1')::uuid,'BAD','BAD',md5('m23')::uuid)$test$,'23503',NULL,'TEN-04 composite FK rejects cross tenant');
select throws_ok($test$update public.memberships set active=false where id=md5('m11')::uuid$test$,'23514','LAST_OWNER','ROLE-03 last owner cannot deactivate');
select throws_ok($test$delete from public.memberships where organization_id=md5('o1')::uuid and role='OWNER'$test$,'23503',NULL,'ROLE-03 owner deletion restricted by FK');
insert into auth.users(id,email,email_confirmed_at) values(md5('lonely')::uuid,'lonely@example.invalid',clock_timestamp());
select private.bootstrap_organization(md5('lonelyorg')::uuid,'Lonely',md5('lonely')::uuid,gen_random_uuid());
select throws_ok($test$delete from public.memberships where organization_id=md5('lonelyorg')::uuid$test$,'23514','LAST_OWNER','ROLE-03 last owner deletion invariant');
select throws_ok($test$update public.audit_log set action='tampered'$test$,'42501','IMMUTABLE','audit append only');
reset role;
select set_config('request.jwt.claims',jsonb_build_object('sub',md5('u11')::uuid,'role','authenticated')::text,true);
set local role authenticated;
set constraints all deferred;
select public.transfer_ownership(md5('o1')::uuid,md5('transfer')::uuid,md5('m12')::uuid,1);
set constraints all immediate;
select ok(((select role from public.memberships where id=md5('m12')::uuid)='OWNER'),'ownership transferred');
select public.transfer_ownership(md5('o1')::uuid,md5('transfer')::uuid,md5('m12')::uuid,1);
select ok(((select count(*) from public.audit_log where action='transfer_ownership')=1),'transfer replay no duplicate audit');
reset role;
select set_config('request.jwt.claims',jsonb_build_object('sub',md5('u12')::uuid,'role','authenticated')::text,true);
set local role authenticated;
select public.manage_membership(md5('o1')::uuid,md5('revoke')::uuid,md5('m11')::uuid,2,'ADMIN',false);
reset role;
select set_config('request.jwt.claims',jsonb_build_object('sub',md5('u11')::uuid,'role','authenticated')::text,true);
set local role authenticated;
select ok(((select count(*) from public.organizations)=0),'ROLE-04 stale identity loses tenant');
select ok(((select count(*) from public.employees)=0),'ROLE-04 stale identity loses rows');
select throws_ok($test$select public.transfer_ownership(md5('o1')::uuid,md5('transfer')::uuid,md5('m12')::uuid,1)$test$,'42501','FORBIDDEN','revoked principal cannot replay receipt');
reset role;
select set_config('request.jwt.claims',jsonb_build_object('sub',md5('u12')::uuid,'role','authenticated')::text,true);
set local role authenticated;
select public.manage_employee(md5('o1')::uuid,md5('create')::uuid,md5('created')::uuid,0,'NEW','No email',null,true);
select public.manage_employee(md5('o1')::uuid,md5('create')::uuid,md5('created')::uuid,0,'NEW','No email',null,true);
select ok(((select count(*) from public.employees where id=md5('created')::uuid and membership_id is null)=1),'no email employee plus idempotent retry');
select ok(((select count(*) from public.audit_log where action='manage_employee')=1),'one audit per mutation');
select throws_ok($test$select public.manage_employee(md5('o1')::uuid,md5('create')::uuid,md5('created')::uuid,0,'OTHER','No email',null,true)$test$,'22023','IDEMPOTENCY_CONFLICT','payload mismatch rejected');
select throws_ok($test$select public.manage_employee(md5('o1')::uuid,gen_random_uuid(),md5('created')::uuid,0,'NEW','No email',null,true)$test$,'40001','VERSION_CONFLICT','stale version rejected');
reset role;
set local role anon;
select throws_ok($test$select * from public.organizations$test$,'42501',NULL,'TEN-06 anon no organizations');
select throws_ok($test$select * from public.memberships$test$,'42501',NULL,'TEN-06 anon no memberships');
select throws_ok($test$select * from public.employees$test$,'42501',NULL,'TEN-06 anon no employees');
select throws_ok($test$select * from public.audit_log$test$,'42501',NULL,'TEN-06 anon no audit_log');
select throws_ok($test$select public.manage_employee(md5('o1')::uuid,gen_random_uuid(),md5('x')::uuid,0,'X','X',null,true)$test$,'42501',NULL,'TEN-06 anon no RPC');
select throws_ok($test$select * from private.idempotency_records$test$,'42501',NULL,'anon no private rows');
reset role;
select set_config('request.jwt.claims',jsonb_build_object('sub',md5('u12')::uuid,'role','authenticated')::text,true);
set local role authenticated;
select throws_ok($test$select private.bootstrap_organization(md5('x')::uuid,'X',md5('u12')::uuid,gen_random_uuid())$test$,'42501',NULL,'no public OWNER bootstrap');
reset role;
select * from finish();
rollback;
